export const MOODS = [
  { label: "Great", emoji: "😊", score: 5 },
  { label: "Okay", emoji: "🙂", score: 4 },
  { label: "Meh", emoji: "😐", score: 3 },
  { label: "Low", emoji: "😟", score: 2 },
  { label: "Overwhelmed", emoji: "😰", score: 1 },
];

export const EXAMS = [
  "NEET",
  "JEE",
  "CUET",
  "CAT",
  "GATE",
  "UPSC",
  "Board Exams",
  "Other",
];

export const FEARS = [
  "Failing",
  "Disappointing Parents",
  "Not Getting Rank",
  "Blanking in Exam",
  "Other",
];

export const SUPPORT_SYSTEMS = ["Family", "Friends", "Mentor", "None"];

export const styles = {
  appShell: {
    backgroundColor: "#0f1724",
    color: "#e2e8f0",
    minHeight: "100vh",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    backgroundColor: "#1a2744",
    padding: "16px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  headerTitleArea: {
    display: "flex",
    flexDirection: "column",
  },
  logo: {
    fontFamily: "'Georgia', serif",
    fontSize: "24px",
    color: "#4ade80",
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  countdownBadge: {
    backgroundColor: "rgba(251, 191, 36, 0.15)",
    border: "1px solid #fbbf24",
    borderRadius: "20px",
    padding: "6px 16px",
  },
  badgeText: {
    color: "#fbbf24",
    fontSize: "14px",
    fontWeight: "600",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "24px",
    maxWidth: "1100px",
    width: "100%",
    margin: "0 auto",
  },
  onboardingCard: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    padding: "32px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
    maxWidth: "600px",
    width: "100%",
    margin: "40px auto",
    animation: "fadeIn 0.4s ease-out",
  },
  onboardingTitle: {
    fontFamily: "'Georgia', serif",
    fontSize: "28px",
    color: "#4ade80",
    marginBottom: "12px",
  },
  onboardingSubtitle: {
    fontSize: "14px",
    color: "#94a3b8",
    lineHeight: "1.6",
    marginBottom: "24px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fieldLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#e2e8f0",
  },
  input: {
    backgroundColor: "#0f1724",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e2e8f0",
    padding: "10px 14px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  inputError: {
    backgroundColor: "#0f1724",
    border: "1px solid #f472b6",
    borderRadius: "8px",
    color: "#e2e8f0",
    padding: "10px 14px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    backgroundColor: "#0f1724",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e2e8f0",
    padding: "10px 14px",
    fontSize: "14px",
    outline: "none",
    cursor: "pointer",
  },
  selectError: {
    backgroundColor: "#0f1724",
    border: "1px solid #f472b6",
    borderRadius: "8px",
    color: "#e2e8f0",
    padding: "10px 14px",
    fontSize: "14px",
    outline: "none",
    cursor: "pointer",
  },
  rangeInput: {
    cursor: "pointer",
    accentColor: "#4ade80",
    width: "100%",
  },
  checkboxContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  btnCheckbox: {
    backgroundColor: "transparent",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: "20px",
    color: "#94a3b8",
    padding: "6px 14px",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  btnCheckboxActive: {
    backgroundColor: "rgba(74, 222, 128, 0.15)",
    border: "1.5px solid #4ade80",
    borderRadius: "20px",
    color: "#4ade80",
    padding: "6px 14px",
    fontSize: "13px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  btnPrimary: {
    backgroundColor: "#fbbf24",
    color: "#0f1724",
    border: "none",
    borderRadius: "8px",
    padding: "12px 24px",
    fontSize: "15px",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    textAlign: "center",
  },
  btnPrimaryDisabled: {
    backgroundColor: "#60a5fa",
    color: "#0f1724",
    border: "none",
    borderRadius: "8px",
    padding: "12px 24px",
    fontSize: "15px",
    fontWeight: "bold",
    cursor: "not-allowed",
    opacity: 0.7,
    textAlign: "center",
  },
  btnSecondary: {
    backgroundColor: "transparent",
    color: "#94a3b8",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: "8px",
    padding: "10px 20px",
    fontSize: "13px",
    cursor: "pointer",
  },
  btnSecondaryDisabled: {
    backgroundColor: "transparent",
    color: "rgba(255,255,255,0.15)",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "8px",
    padding: "10px 20px",
    fontSize: "13px",
    cursor: "not-allowed",
  },
  errorText: {
    color: "#f472b6",
    fontSize: "12px",
    marginTop: "2px",
  },
  dashboardLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    outline: "none",
  },
  tabList: {
    display: "flex",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    overflowX: "auto",
    gap: "8px",
  },
  tabBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#94a3b8",
    padding: "12px 20px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    borderBottom: "3px solid transparent",
    whiteSpace: "nowrap",
  },
  tabBtnActive: {
    backgroundColor: "transparent",
    border: "none",
    color: "#4ade80",
    padding: "12px 20px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    borderBottom: "3px solid #4ade80",
    whiteSpace: "nowrap",
  },
  tabContentPanel: {
    minHeight: "450px",
    animation: "fadeIn 0.3s ease-out",
  },
  card: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
  },
  cardTitle: {
    fontFamily: "'Georgia', serif",
    fontSize: "20px",
    color: "#e2e8f0",
    marginBottom: "18px",
  },
  moodButtonGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  moodBtn: {
    backgroundColor: "#0f1724",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "12px",
    color: "#e2e8f0",
    padding: "10px 14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "transform 0.2s ease",
  },
  moodBtnActive: {
    backgroundColor: "rgba(74, 222, 128, 0.15)",
    border: "2px solid #4ade80",
    borderRadius: "12px",
    color: "#4ade80",
    padding: "10px 14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transform: "scale(1.05)",
  },
  moodEmoji: {
    fontSize: "20px",
  },
  moodLabel: {
    fontSize: "13px",
    fontWeight: "600",
  },
  textareaHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  charCounter: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  textarea: {
    backgroundColor: "#0f1724",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e2e8f0",
    fontFamily: "'Georgia', serif",
    fontSize: "15px",
    lineHeight: "1.7",
    padding: "12px",
    outline: "none",
    resize: "vertical",
    width: "100%",
    boxSizing: "border-box",
  },
  textareaError: {
    backgroundColor: "#0f1724",
    border: "1px solid #f472b6",
    borderRadius: "8px",
    color: "#e2e8f0",
    fontFamily: "'Georgia', serif",
    fontSize: "15px",
    lineHeight: "1.7",
    padding: "12px",
    outline: "none",
    resize: "vertical",
    width: "100%",
    boxSizing: "border-box",
  },
  spinnerWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px",
    gap: "12px",
  },
  spinner: {
    width: "40px",
    height: "40px",
    border: "4px solid rgba(255,255,255,0.1)",
    borderTopColor: "#4ade80",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  spinnerText: {
    color: "#94a3b8",
    fontSize: "14px",
  },
  insightCard: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    borderLeft: "6px solid",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
    animation: "fadeIn 0.3s ease-out",
    outline: "none",
  },
  insightHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  insightTitle: {
    fontFamily: "'Georgia', serif",
    fontSize: "18px",
    color: "#4ade80",
  },
  badgeLow: {
    backgroundColor: "rgba(74, 222, 128, 0.15)",
    border: "1px solid #4ade80",
    color: "#4ade80",
    borderRadius: "20px",
    padding: "4px 10px",
    fontSize: "11px",
    fontWeight: "bold",
  },
  badgeMed: {
    backgroundColor: "rgba(251, 191, 36, 0.15)",
    border: "1px solid #fbbf24",
    color: "#fbbf24",
    borderRadius: "20px",
    padding: "4px 10px",
    fontSize: "11px",
    fontWeight: "bold",
  },
  badgeHigh: {
    backgroundColor: "rgba(244, 114, 182, 0.15)",
    border: "1px solid #f472b6",
    color: "#f472b6",
    borderRadius: "20px",
    padding: "4px 10px",
    fontSize: "11px",
    fontWeight: "bold",
  },
  insightText: {
    fontSize: "14px",
    lineHeight: "1.5",
  },
  triggersSection: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    fontSize: "14px",
  },
  tagGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  triggerTag: {
    backgroundColor: "#0f1724",
    borderRadius: "6px",
    padding: "4px 8px",
    fontSize: "12px",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  copingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "12px",
  },
  copingCard: {
    backgroundColor: "#0f1724",
    borderRadius: "12px",
    padding: "14px",
    border: "1px solid rgba(255,255,255,0.05)",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  copingCardTitle: {
    color: "#60a5fa",
    fontSize: "14px",
    fontWeight: "bold",
  },
  copingCardDesc: {
    fontSize: "12px",
    color: "#94a3b8",
    lineHeight: "1.4",
  },
  copingFooter: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "11px",
    color: "#94a3b8",
    marginTop: "auto",
  },
  affirmationBox: {
    borderTop: "1px solid rgba(255,255,255,0.08)",
    paddingTop: "12px",
  },
  affirmationText: {
    fontFamily: "'Georgia', serif",
    fontStyle: "italic",
    fontSize: "14px",
    color: "#fbbf24",
    textAlign: "center",
  },
  followUpBox: {
    backgroundColor: "rgba(96, 165, 250, 0.08)",
    padding: "10px 14px",
    borderRadius: "8px",
    borderLeft: "4px solid #60a5fa",
  },
  followUpText: {
    fontSize: "13px",
    color: "#e2e8f0",
  },
  pastEntriesSection: {
    marginTop: "24px",
  },
  subHeading: {
    fontFamily: "'Georgia', serif",
    fontSize: "18px",
    marginBottom: "12px",
  },
  entriesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  entryRow: {
    backgroundColor: "#1a2744",
    borderRadius: "12px",
    padding: "16px",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  entryRowMeta: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
    paddingBottom: "8px",
  },
  entryRowEmoji: {
    fontSize: "24px",
  },
  entryRowDetails: {
    display: "flex",
    flexDirection: "column",
  },
  entryRowMood: {
    fontSize: "14px",
  },
  entryRowTime: {
    fontSize: "11px",
    color: "#94a3b8",
  },
  entryRowEnergy: {
    marginLeft: "auto",
    fontSize: "12px",
    color: "#fbbf24",
    fontWeight: "bold",
  },
  entryRowText: {
    fontSize: "13px",
    lineHeight: "1.6",
    color: "#94a3b8",
  },
  chatContainer: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    height: "550px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
    overflow: "hidden",
  },
  chatHeader: {
    backgroundColor: "#0f1724",
    padding: "16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  chatTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "4px",
  },
  companionIndicator: {
    color: "#4ade80",
    fontSize: "10px",
  },
  chatHeading: {
    fontFamily: "'Georgia', serif",
    fontSize: "16px",
  },
  companionDesc: {
    fontSize: "11px",
    color: "#94a3b8",
  },
  chatWindow: {
    flex: 1,
    padding: "16px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  chatRowUser: {
    display: "flex",
    justifyContent: "flex-end",
  },
  chatRowCompanion: {
    display: "flex",
    justifyContent: "flex-start",
  },
  bubbleUser: {
    backgroundColor: "#fbbf24",
    color: "#0f1724",
    borderRadius: "16px 16px 2px 16px",
    padding: "10px 14px",
    maxWidth: "75%",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
  },
  bubbleCompanion: {
    backgroundColor: "#0f1724",
    color: "#e2e8f0",
    borderRadius: "16px 16px 16px 2px",
    padding: "10px 14px",
    maxWidth: "75%",
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  chatText: {
    fontSize: "14px",
    lineHeight: "1.5",
  },
  chatTime: {
    fontSize: "10px",
    color: "rgba(0,0,0,0.4)",
    display: "block",
    textAlign: "right",
    marginTop: "4px",
  },
  typingIndicator: {
    display: "flex",
    gap: "4px",
    padding: "4px 8px",
  },
  chatInputArea: {
    backgroundColor: "#0f1724",
    padding: "12px",
    display: "flex",
    gap: "8px",
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  chatInput: {
    flex: 1,
    backgroundColor: "#1a2744",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e2e8f0",
    padding: "10px 14px",
    outline: "none",
  },
  btnSend: {
    backgroundColor: "#fbbf24",
    color: "#0f1724",
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  btnSendDisabled: {
    backgroundColor: "#1a2744",
    color: "#94a3b8",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "8px",
    padding: "10px 16px",
    cursor: "not-allowed",
  },
  mindfulnessLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  mindfulnessHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tabHeading: {
    fontFamily: "'Georgia', serif",
    fontSize: "20px",
  },
  exerciseGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "16px",
  },
  exerciseCard: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    padding: "20px",
    border: "1px solid rgba(255,255,255,0.05)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  exerciseHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  exerciseEmoji: {
    fontSize: "32px",
  },
  exerciseName: {
    fontFamily: "'Georgia', serif",
    fontSize: "16px",
    color: "#4ade80",
  },
  exerciseDuration: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  exerciseSteps: {
    fontSize: "13px",
  },
  stepsList: {
    paddingLeft: "20px",
    marginTop: "6px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  stepItem: {
    color: "#e2e8f0",
  },
  whyBox: {
    backgroundColor: "rgba(74, 222, 128, 0.08)",
    padding: "8px 12px",
    borderRadius: "8px",
    marginTop: "auto",
  },
  whyText: {
    fontSize: "12px",
    color: "#4ade80",
    lineHeight: "1.4",
  },
  patternsHoldState: {
    textAlign: "center",
    padding: "48px 24px",
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
  },
  holdEmoji: {
    fontSize: "48px",
    display: "block",
    marginBottom: "16px",
  },
  holdText: {
    color: "#94a3b8",
    fontSize: "14px",
    marginTop: "8px",
  },
  patternsLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  patternsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  chartCard: {
    backgroundColor: "#1a2744",
    borderRadius: "16px",
    padding: "20px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
  },
  chartTitle: {
    fontFamily: "'Georgia', serif",
    fontSize: "16px",
    marginBottom: "16px",
  },
  chartWrapper: {
    display: "flex",
    height: "180px",
    gap: "12px",
  },
  chartAxisY: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    fontSize: "11px",
    color: "#94a3b8",
    textAlign: "right",
    paddingRight: "8px",
  },
  chartArea: {
    flex: 1,
    display: "flex",
    alignItems: "flex-end",
    gap: "8px",
    borderLeft: "1px solid rgba(255,255,255,0.1)",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    paddingLeft: "8px",
    paddingBottom: "4px",
    overflowX: "auto",
  },
  chartBarCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    minWidth: "24px",
    height: "100%",
    justifyContent: "flex-end",
  },
  chartBar: {
    width: "100%",
    borderRadius: "4px 4px 0 0",
    transition: "height 0.3s ease",
  },
  chartBarLabel: {
    fontSize: "11px",
    color: "#94a3b8",
    marginTop: "4px",
  },
  chartCaption: {
    fontSize: "11px",
    color: "#94a3b8",
    marginTop: "10px",
    textAlign: "center",
  },
  patternsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "16px",
  },
  triggerStack: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  triggerPatternRow: {
    backgroundColor: "#0f1724",
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  triggerPatternMeta: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "4px",
  },
  triggerPatternTitle: {
    fontSize: "14px",
    color: "#fbbf24",
  },
  triggerPatternFreq: {
    fontSize: "11px",
    backgroundColor: "rgba(251, 191, 36, 0.15)",
    padding: "2px 6px",
    borderRadius: "4px",
    color: "#fbbf24",
  },
  triggerPatternExplain: {
    fontSize: "12px",
    color: "#94a3b8",
    lineHeight: "1.4",
  },
  trendBoxGreen: {
    backgroundColor: "rgba(74, 222, 128, 0.08)",
    border: "1px solid #4ade80",
    borderRadius: "8px",
    padding: "12px",
    marginBottom: "16px",
  },
  trendBoxYellow: {
    backgroundColor: "rgba(251, 191, 36, 0.08)",
    border: "1px solid #fbbf24",
    borderRadius: "8px",
    padding: "12px",
    marginBottom: "16px",
  },
  trendBoxRed: {
    backgroundColor: "rgba(244, 114, 182, 0.08)",
    border: "1px solid #f472b6",
    borderRadius: "8px",
    padding: "12px",
    marginBottom: "16px",
  },
  trendValue: {
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "4px",
  },
  trendDesc: {
    fontSize: "12px",
    color: "#e2e8f0",
  },
  hiddenPatternBox: {
    backgroundColor: "#0f1724",
    borderRadius: "8px",
    padding: "12px",
  },
  hiddenPatternTitle: {
    fontSize: "13px",
    color: "#60a5fa",
    marginBottom: "4px",
  },
  hiddenPatternText: {
    fontSize: "12px",
    color: "#94a3b8",
    lineHeight: "1.4",
  },
  actionPlanList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  actionPlanCard: {
    backgroundColor: "#0f1724",
    borderRadius: "8px",
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  actionStepNum: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    backgroundColor: "rgba(74, 222, 128, 0.15)",
    color: "#4ade80",
    fontWeight: "bold",
    fontSize: "12px",
  },
  actionStepText: {
    fontSize: "13px",
    color: "#e2e8f0",
  },
  errorBanner: {
    backgroundColor: "rgba(244, 114, 182, 0.15)",
    border: "1px solid #f472b6",
    borderRadius: "8px",
    padding: "12px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  errorBannerText: {
    color: "#f472b6",
    fontSize: "14px",
  },
  errorDismissBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#f472b6",
    cursor: "pointer",
    fontSize: "14px",
  },
  journalLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  calendarDropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    width: "280px",
    backgroundColor: "#1a2744",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: "12px",
    padding: "12px",
    zIndex: 1000,
    boxShadow: "0 10px 25px rgba(0,0,0,0.5)",
    marginTop: "6px",
    animation: "fadeIn 0.2s ease-out",
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  calNavBtn: {
    background: "transparent",
    border: "none",
    color: "#4ade80",
    fontSize: "12px",
    cursor: "pointer",
    padding: "4px 8px",
  },
  calTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#e2e8f0",
  },
  calDayNames: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    textAlign: "center",
    marginBottom: "6px",
  },
  calDayNameLabel: {
    fontSize: "11px",
    color: "#94a3b8",
    fontWeight: "bold",
  },
  calDaysGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: "4px",
  },
  calDayEmpty: {
    height: "28px",
  },
  calDayCell: {
    height: "28px",
    background: "transparent",
    border: "none",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.2s ease",
  },
  calDayDisabled: {
    color: "rgba(255,255,255,0.15)",
    cursor: "not-allowed",
  },
  calDaySelected: {
    backgroundColor: "#4ade80",
    color: "#0f1724",
    fontWeight: "bold",
  },
};

export const KEYFRAME_CSS = `
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  @keyframes bounce {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-6px); }
  }
  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }
`;
